- hosts: "all"
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
    - name: Setup PostgreSQL server
      import_role:
        name: "geerlingguy.postgresql"
      vars:
        #TODO fill in postgres vars and complete psql options
    - name:
      shell: "wget -O - {{ initial_db_uri }} | gzip -d | psql"